---
# tasks file for LAMP
- name: Install httpd
  yum: 
    name: httpd
    state: present
- name: starting httpd
  service:
    name: httpd
    enabled: true
    state: started
- name: Install MariaDB
  yum:
    name: mariadb-server
    state: present
- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes
- name: Install pip
  yum:
    name: pip
    state: present
- pip:
    name: pymysql
- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    login_user: '{{ u }}'
    login_password: '{{ p }}'
    name: root 
    password: root
    priv: '*.*:ALL,GRANT'
    state: present 
- name: Grant privileges to root user
  mysql_user:
    login_user: root
    login_password: root
      #host: '{{ h }}'
    name: lipu
    password: lipu 
    priv: "*.*:ALL"
    state: present 
- name: Configure MariaDB to listen on all interfaces
  lineinfile:
    dest: /etc/my.cnf 
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
- name: Enable PHP 8.1 repository
  shell:
    cmd: amazon-linux-extras install php8.2 -y
- name: install phpmyadmin
  get_url: 
    url: https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-english.zip
    dest: /var/www/html
- name: installing unzip
  yum:
    name: unzip
    state: present
- name: unziping the file
  unarchive:
    src: /var/www/html/phpMyAdmin-5.2.1-english.zip
    dest: /var/www/html/
    remote_src: yes
- name: renaming
  shell:
    chdir: /var/www/html/
    cmd: mv phpMyAdmin-5.2.1-english phpMyAdmin
- name: removing the zip file which i have downloaded
  shell:
    chdir: /var/www/html/
    cmd: rm -rf phpMyAdmin-5.2.1-english.zip
- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
- name: restart httpd
  service:
    name: httpd 
    state: restarted
