---
- hosts: module1
  become: true
  tasks:
    - name: installing apache2
      yum:
        name: apache2
        state: present
          #- name: adding the html file
          #copy:
          #src: ./index.html
          #dest: /var/www/html
